config/routes.rb
Rails.application.routes.draw do
  root 'ponies#new'
  resources :ponies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pony.rb
class Pony < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ponies_controller.rb
class PoniesController < ApplicationController
  before_action :set_pony, only: %i[ show edit update destroy ]

  # GET /ponies or /ponies.json
  def index
    @ponies = Pony.all
  end

  # GET /ponies/1 or /ponies/1.json
  def show
  end

  # GET /ponies/new
  def new
    @pony = Pony.new
  end

  # GET /ponies/1/edit
  def edit
  end

  # POST /ponies or /ponies.json
  def create
    @pony = Pony.new(pony_params)

    respond_to do |format|
      if @pony.save
        format.html { redirect_to @pony, notice: "Pony was successfully created." }
        format.json { render :show, status: :created, location: @pony }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ponies/1 or /ponies/1.json
  def update
    respond_to do |format|
      if @pony.update(pony_params)
        format.html { redirect_to @pony, notice: "Pony was successfully updated." }
        format.json { render :show, status: :ok, location: @pony }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pony.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ponies/1 or /ponies/1.json
  def destroy
    @pony.destroy
    respond_to do |format|
      format.html { redirect_to ponies_url}
      format.json { head :no_content }
      format.js   { flash[:notice] = "Pony was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pony
      @pony = Pony.find_by_id(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pony_params
      params.require(:pony).permit(:name, :profession)
    end
end
 


 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ponies_helper.rb
module PoniesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD_AJAX_RAILS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ponies/_form.html.erb
<%= form_with(model: pony) do |form| %>
  <% if pony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pony.errors.count, "error") %> prohibited this pony from being saved:</h2>

      <ul>
        <% pony.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :profession %>
    <%= form.text_field :profession %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ponies/destroy.js.erb
$('.delete').on('ajax:success', function() {
	// alert("The paragraph was clicked.");
	$("#notice").html("<%= notice %>");
	
   $(this).closest('tr').fadeOut();

});

app/views/ponies/edit.html.erb
<h1>Editing Pony</h1>

<%= render 'form', pony: @pony %>

<%= link_to 'Show', @pony %> |
<%= link_to 'Back', ponies_path %>

app/views/ponies/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>Ponies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Profession</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%if @ponies.present?%>
    <% @ponies.each do |pony| %>
      <tr>
        <td><%= pony.name %></td>
        <td><%= pony.profession %></td>
        <td><%= link_to 'Show', pony %></td>
        <td><%= link_to 'Edit', edit_pony_path(pony) %></td>
        <td><%= link_to 'Destroy', pony,method: :delete, data:{ confirm: 'Are you sure?'}, :remote => true, :class => 'delete' %></td>
      </tr>
    <% end %>
    <%else%>
    <td> 'No record found.'</td>
    <%end%>
  </tbody>
</table>

<br>

<%= link_to 'New Pony', new_pony_path %>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

app/views/ponies/new.html.erb
<h1>New Pony</h1>

<%= render 'form', pony: @pony %>

<%= link_to 'Back', ponies_path %>

app/views/ponies/show.html.erb
<p id="notice"><%= notice %></p>
<%if @pony.present? %>
<p>
  <strong>Name:</strong>
  <%= @pony.name %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @pony.profession %>
</p>


<%= link_to 'Edit', edit_pony_path(@pony) %> |
<%else%>
<p class="danger">No record found</p>
<%end%>
<%= link_to 'Back', ponies_path %>